
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://fsiowgdqaxjyemxtfbok.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzaW93Z2RxYXhqeWVteHRmYm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODMwMDIsImV4cCI6MjA2MDQ1OTAwMn0.vjTb0CwbSfngCEaDpDj-8xRN4l0B7liS8D5G7Rss7WQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
